=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/blockOut.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="window" type="windowType"/>
    <xs:element name="layout" type="layoutType"/>

    <xs:complexType name="windowType">
        <xs:group ref="paneContainerGroup" minOccurs="0" maxOccurs="unbounded"/>
        <xs:attribute name="inherit"  type="xs:string"/>
        <xs:attribute name="size"     type="xs:string"/>
        <xs:attribute name="width"    type="xs:string"/>
        <xs:attribute name="height"   type="xs:string"/>
        <xs:attribute name="lightbox" type="xs:boolean"/>
        <xs:attribute name="pause"    type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="layoutType">
        <xs:group ref="paneContainerGroup" minOccurs="0" maxOccurs="unbounded"/>
    </xs:complexType>

    <!-- Pane basic attributes -->
    <xs:complexType name="paneType">
        <xs:attribute name="id"      type="xs:string"/>

        <xs:attribute name="align"   type="xs:string"/>
        <xs:attribute name="size"    type="xs:string"/>
        <xs:attribute name="width"   type="xs:string"/>
        <xs:attribute name="height"  type="xs:string"/>
        <xs:attribute name="pos"     type="xs:string"/>
        <xs:attribute name="x"       type="xs:string"/>
        <xs:attribute name="y"       type="xs:string"/>

        <xs:attribute name="visible" type="xs:boolean"/>
        <xs:attribute name="enabled" type="xs:boolean"/>

        <xs:attribute name="style"   type="xs:string"/>
    </xs:complexType>

    <!-- View basic attributes and contents -->
    <xs:complexType name="viewType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:group ref="paneContainerGroup" minOccurs="0" maxOccurs="unbounded"/>
                <xs:attribute name="padding" type="xs:integer"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- Master group for all panes that can be used -->
    <xs:group name="paneContainerGroup">
        <xs:choice>
            <xs:element name="layout"       type="layoutElementType"/>
            <xs:element name="view"         type="viewType"/>
            <xs:element name="group"        type="groupType"/>
            <!-- xs:element name="scrollgroup"  type="scrollGroupType"/ -->
            <xs:element name="list"         type="listType"/>
            <xs:element name="button"       type="buttonType"/>
            <xs:element name="buttonimage"  type="buttonImageType"/>
            <xs:element name="label"        type="labelType"/>
            <xs:element name="input"        type="inputType"/>
            <xs:element name="image"        type="imageType"/>
            <xs:element name="box"          type="boxType"/>
            <xs:element name="itemicon"     type="itemIconType"/>
            <xs:element name="switch"       type="switchType"/>
        </xs:choice>
    </xs:group>

    <!-- <layout> -->
    <xs:complexType name="layoutElementType">
        <xs:attribute name="source" use="required"/>
    </xs:complexType>

    <!-- <group> -->
    <xs:complexType name="groupType">
        <xs:complexContent>
            <xs:extension base="viewType">
                <xs:attribute name="spacing" type="xs:integer"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <switch> -->
    <xs:complexType name="switchType">
        <xs:complexContent>
            <xs:extension base="viewType">
                <xs:attribute name="default" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <box> -->
    <xs:complexType name="boxType">
        <xs:complexContent>
            <xs:extension base="viewType">
                <xs:attribute name="color" type="xs:string"/>
                <xs:attribute name="linewidth" type="xs:decimal"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <list> -->
    <xs:complexType name="listType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:group ref="paneContainerGroup" minOccurs="1" maxOccurs="1"/>
                <xs:attribute name="padding" type="xs:integer"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <button> -->
    <xs:complexType name="buttonType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="label"      type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <label> -->
    <xs:complexType name="labelType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="label"      type="xs:string"/>
                <xs:attribute name="textscale"  type="xs:string"/>
                <xs:attribute name="textalign"  type="xs:string"/>
                <xs:attribute name="color"      type="xs:string"/>
                <xs:attribute name="hovercolor" type="xs:string"/>
                <xs:attribute name="shadow"     type="xs:boolean"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <itemicon> -->
    <xs:complexType name="itemIconType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="item" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <buttonimage> -->
    <xs:complexType name="buttonImageType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <!-- Image and Highlight -->
                <xs:attribute name="source"          type="xs:string" use="required"/>
                <xs:attribute name="imageoffset"     type="xs:string"/>
                <xs:attribute name="imagesize"       type="xs:string"/>
                <xs:attribute name="highlight"       type="xs:string"/>
                <xs:attribute name="highlightoffset" type="xs:string"/>
                <xs:attribute name="highlightsize"   type="xs:string"/>
                <!-- Label (optional) -->
                <xs:attribute name="label"      type="xs:string"/>
                <xs:attribute name="textscale"       type="xs:string"/>
                <xs:attribute name="textalign"       type="xs:string"/>
                <xs:attribute name="textoffset"      type="xs:string"/>
                <xs:attribute name="textcolor"       type="xs:string"/>
                <xs:attribute name="texthovercolor"  type="xs:string"/>
                <xs:attribute name="textdisabledcolor" type="xs:string"/>
                <xs:attribute name="shadow"          type="xs:boolean"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <image> -->
    <xs:complexType name="imageType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="source" type="xs:string"/>
                <xs:attribute name="imageoffset" type="xs:string"/>
                <xs:attribute name="imagesize" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <input> -->
    <xs:complexType name="inputType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="text"          type="xs:string"/>
                <xs:attribute name="maxlength"     type="xs:integer"/>
                <xs:attribute name="color"         type="xs:string"/>
                <xs:attribute name="colordisabled" type="xs:string"/>
                <xs:attribute name="shadow"        type="xs:boolean"/>
                <xs:attribute name="tab"           type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

</xs:schema>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/windowhutcomposter.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" size="190 244" pause="false"
        lightbox="false"
        xsi:noNamespaceSchemaLocation="file:../../../../java/com/minecolonies/blockout/blockOut.xsd">
    <switch id="pages" size="100% 100%">
	    <view id="pageActions" size="100% 100%">
        	<layout source="minecolonies:gui/windowworkerbuildingdefault.xml"/>
    	</view>
        <view id="pageRecipes" size="100% 100%" pos="0 1">
            <layout source="minecolonies:gui/windowbase.xml"/>
            <label size="100% 11" pos="0 40" label="Recipes:" color="black" textalign="BOTTOM_MIDDLE"/>

            <list id="recipes" size="85% 120" pos="5 60" align="TOP_MIDDLE">
                <view size="100% 30">
                    <box size="100% 30" linewidth="2">
                        <button id="assignRecipe" pos="95 10" size="40 15"/>
                        <label id="name" color="black" pos="20 5"/>
                        <itemicon id="icon" size="16 16" pos="0 0"/>
                    </box>
                </view>
            </list>
        </view>
    </switch>
    <buttonimage id="prevPage" align="TOP_LEFT" size="26 8" pos="12 15" source="minecolonies:textures/gui/builderhut/builder_sketch_arrow_left_c.png"/>
    <buttonimage id="nextPage" align="TOP_RIGHT" size="26 8" pos="12 15" source="minecolonies:textures/gui/builderhut/builder_sketch_arrow_right_c.png"/>
</window>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/windowtestgui.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" size="190 244" pause="false" lightbox="false"
        xsi:noNamespaceSchemaLocation="file:../../../../../api/java/com/minecolonies/blockout/blockOut.xsd">
    <image source="minecolonies:textures/gui/builderhut/builder_paper.png" size="190 244"/>
    <label id="title"
           size="100% 11" pos="0 9"
           textalign="TOP_MIDDLE"
           color="0"
           label="$(com.minecolonies.coremod.gui.citizen.skills)"/>
    <group width="100" height="55" x="30" y="30">
        <label id="strength"
               width="100%" height="11"
               color="0"/>
        <label id="stamina"
               width="100%" height="11"
               color="black"/>
        <label id="wisdom"
               width="100%" height="11"
               color="#ff0000"/>
        <!-- label id="intelligence"
               width="100%" height="11"
               color="rgb(255,0,0)" />
        <label id="charisma"
               width="100%" height="11"
               color="rgba(0,255,0,0.5)" / -->
        <itemicon item="gold_ingot"/>
    </group>
    <view size="80% 60" y="85" align="TOP_MIDDLE">
        <input id="text1"
               size="100% 20" y="0" text="This is just a test"
               tab="text2"/>
        <input id="text2"
               size="100% 20" y="20" text="This is just a test"
               tab="text1"/>
    </view>
    <!-- box padding="3" size="100 85" y="128" align="TOP_MIDDLE">
        <list id="scrollgroup"
              size="100%">
            <view size="100% 45px">
                <label id="listlabel" width="-35" height="11" color="black" hovercolor="white" label="1" />
                <button id="listbutton" width="30" height="11" x="5" y="0" align="TOP_RIGHT" label="B" />
                <list id="scrollgroup2" width="100%" height="30" y="12">
                    <label id="listlabel2" height="11" color="black" hovercolor="white" label="1" />
                </list>
            </view>
        </list>
    </box -->
    <box size="80% 85" pos="0 128" align="TOP_MIDDLE">
        <text size="100% 100%" color="black" textscale="1.0">
            This is just a test of text!
            The text has multiple lines...
            So let's see if it really works...
            It should also wrap on it's own.
        </text>
    </box>

    <button id="inventory"
            align="BOTTOM_MIDDLE" size="116 20" pos="0 13"
            label="$(container.inventory)"/>
</window>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/windowhutguardtower.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" size="190 244" pause="false"
        lightbox="false"
        xsi:noNamespaceSchemaLocation="file:../../../../java/com/minecolonies/blockout/blockOut.xsd">
    <switch id="pages" size="100% 100%">
        <view id="pageActions" size="100% 100%">
            <layout source="minecolonies:gui/windowworkerbuildingdefault.xml"/>
        </view>

        <view id="levelActions" size="100% 100%">
            <layout source="minecolonies:gui/windowbase.xml"/>
            <label size="100% 11" pos="0 10"
                   label="$(com.minecolonies.coremod.gui.workerHuts.guardActions)" color="black"
                   textalign="BOTTOM_MIDDLE"/>

            <buttonimage id="job" size="86 17" pos="40 25"
                         source="minecolonies:textures/gui/builderhut/builder_button_medium.png"
                         label="$(com.minecolonies.coremod.gui.workerHuts.knight)" textcolor="black"/>

            <label size="50% 11" pos="40 40" label="$(com.minecolonies.coremod.gui.workerHuts.assign)" color="black"
                   textalign="BOTTOM_MIDDLE"/>
            <buttonimage id="assign" size="86 17" pos="40 55"
                         source="minecolonies:textures/gui/builderhut/builder_button_medium.png"
                         label="$(com.minecolonies.coremod.gui.workerHuts.modeA)" textcolor="black"/>

            <label size="50% 11" pos="40 70" label="$(com.minecolonies.coremod.gui.workerHuts.patrol)" color="black"
                   textalign="BOTTOM_MIDDLE"/>
            <buttonimage id="patrol" size="86 17" pos="40 85"
                         source="minecolonies:textures/gui/builderhut/builder_button_medium.png"
                         label="$(com.minecolonies.coremod.gui.workerHuts.modeA)" textcolor="black"/>

            <label size="50% 11" pos="40 100" label="$(com.minecolonies.coremod.gui.workerHuts.retrieve)" color="black"
                   textalign="BOTTOM_MIDDLE"/>
            <buttonimage id="retrieve" size="86 17" pos="40 115"
                         source="minecolonies:textures/gui/builderhut/builder_button_medium.png"
                         label="$(com.minecolonies.coremod.gui.workerHuts.retrieveOff)" textcolor="black"/>

            <button id="patrolling" size="30% 14" pos="10 135"
                    label="$(com.minecolonies.coremod.gui.workerHuts.task.patrol)"/>
            <button id="following" size="30% 14" pos="62 135"
                    label="$(com.minecolonies.coremod.gui.workerHuts.task.follow)"/>
            <button id="guarding" size="30% 14" pos="114 135"
                    label="$(com.minecolonies.coremod.gui.workerHuts.task.guard)"/>

            <buttonimage id="setTarget" size="129 17" pos="25 160"
                         source="minecolonies:textures/gui/builderhut/builder_button_medium_large.png"
                         label="$(com.minecolonies.coremod.gui.workerHuts.setTarget)" textcolor="black"/>

            <list id="positions" size="78% 50" pos="30 165">
                <box size="100% 15" linewidth="2">
                    <label id="position" size="100 12" pos="5 2" textalign="MIDDLE_LEFT" color="black"/>
                </box>
            </list>

        </view>


    </switch>
    <buttonimage id="prevPage" align="TOP_LEFT" size="26 8" pos="12 15" source="minecolonies:textures/gui/builderhut/builder_sketch_arrow_left_c.png"/>
    <buttonimage id="nextPage" align="TOP_RIGHT" size="26 8" pos="12 15" source="minecolonies:textures/gui/builderhut/builder_sketch_arrow_right_c.png"/>
</window>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/windowhutallinventory.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" pause="true"
        lightbox="true"
        size="190 244"
        xsi:noNamespaceSchemaLocation="file:../../../../../api/java/com/minecolonies/blockout/blockOut.xsd">
    <image source="minecolonies:textures/gui/builderhut/builder_paper.png" size="190 244"/>
    <label id="desc" size="130 11" pos="30 14" color="black" textalign="MIDDLE" label="$(com.minecolonies.coremod.gui.allinventory)"/>
    <input id="names" size="132 18" pos="15 30" maxlength="25"/>
    <buttonimage id="sortStorageFilter" size="14 15" pos="158 31" textcolor="black"
                 source="minecolonies:textures/gui/builderhut/builder_button_mini.png"
                 label="v^"/>
    <list id="allinventorylist" size="165 156" pos="15 55">
        <box size="100% 18" linewidth="2">
            <itemicon id="resourceIcon" size="17 17" pos="0 0"/>
            <label id="ressourceStackName" size="100 12" pos="20 3" color="black"/>
            <label id="quantities" size="25 18" pos="117 1" color="black"/>
            <buttonimage id="locate" size="14 15" pos="141 1" textcolor="black"
                         source="minecolonies:textures/gui/builderhut/builder_button_mini.png"
                         label="?"/>
        </box>
    </list>
    <buttonimage id="back" size="86 17" pos="50 215" textcolor="black"
                 source="minecolonies:textures/gui/builderhut/builder_button_medium.png"
                 label="$(com.minecolonies.coremod.gui.back)"/>
</window>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/townhall/windowtownhall.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" size="524 243" pause="false" lightbox="false"
        xsi:noNamespaceSchemaLocation="file:../../../../java/com/minecolonies/blockout/blockOut.xsd">

    <image source="minecolonies:textures/gui/townhall_book.png" pos="75 0" size="374 243"/>

    <image id="infopage0" pos="56 73" size="31 14" source="minecolonies:textures/gui/bookmark_short_ribbon_01.png" tooltip="$(com.minecolonies.coremod.gui.townhalltab.information)"/>
    <image id="actions0" pos="56 97" size="31 14" source="minecolonies:textures/gui/bookmark_short_ribbon_02.png" tooltip="$(com.minecolonies.coremod.gui.townhalltab.actions)"/>
    <image id="permissions0" pos="56 121" size="31 15" source="minecolonies:textures/gui/bookmark_short_ribbon_03.png" tooltip="$(com.minecolonies.coremod.gui.townhalltab.permissions)"/>
    <image id="citizens0" pos="56 145" size="31 14" source="minecolonies:textures/gui/bookmark_short_ribbon_04.png" tooltip="$(com.minecolonies.coremod.gui.townhalltab.citizens)"/>
    <image id="settings0" pos="56 169" size="31 14" source="minecolonies:textures/gui/bookmark_short_ribbon_05.png" tooltip="$(com.minecolonies.coremod.gui.townhalltab.settings)"/>
    <image id="workOrder0" pos="56 193" size="31 14" source="minecolonies:textures/gui/bookmark_short_ribbon_06.png" tooltip="$(com.minecolonies.coremod.gui.townhalltab.workorders)"/>
    <image id="happiness0" pos="56 217" size="31 14" source="minecolonies:textures/gui/bookmark_short_ribbon_01.png" tooltip="$(com.minecolonies.coremod.gui.townhalltab.happiness)"/>

    <buttonimage id="infopage1" size="204 17" pos="58 43" source="minecolonies:textures/gui/bookmark_ribbon_01.png" visible="false"
                 label="$(com.minecolonies.coremod.gui.workerhuts.information)"
                 textalign="MIDDLE_LEFT" textoffset="35 2" textcolor="White" textdisabledcolor="DarkGray"/>
    <buttonimage id="actions1" size="204 17" pos="58 43" source="minecolonies:textures/gui/bookmark_ribbon_02.png" visible="false"
                 label="$(com.minecolonies.coremod.gui.townHall.actions)"
                 textalign="MIDDLE_LEFT" textoffset="35 2" textcolor="White" textdisabledcolor="DarkGray"/>
    <buttonimage id="permissions1" size="204 17" pos="58 43" source="minecolonies:textures/gui/bookmark_ribbon_03.png" visible="false"
                 label="$(com.minecolonies.coremod.gui.townHall.permissions)"
                 textalign="MIDDLE_LEFT" textoffset="35 2" textcolor="White" textdisabledcolor="DarkGray"/>
    <buttonimage id="citizens1" size="204 17" pos="58 43" source="minecolonies:textures/gui/bookmark_ribbon_04.png" visible="false"
                 label="$(com.minecolonies.coremod.gui.townHall.citizens)"
                 textalign="MIDDLE_LEFT" textoffset="35 2" textcolor="White" textdisabledcolor="DarkGray"/>
    <buttonimage id="settings1" size="204 17" pos="58 43" source="minecolonies:textures/gui/bookmark_ribbon_05.png" visible="false"
                 label="$(com.minecolonies.coremod.gui.workerhuts.settings)"
                 textalign="MIDDLE_LEFT" textoffset="35 2" textcolor="White" textdisabledcolor="DarkGray"/>
    <buttonimage id="workOrder1" size="204 17" pos="58 43" source="minecolonies:textures/gui/bookmark_ribbon_06.png" visible="false"
                 label="$(com.minecolonies.coremod.gui.workerhuts.workOrder)"
                 textalign="MIDDLE_LEFT" textoffset="35 2" textcolor="White" textdisabledcolor="DarkGray"/>
    <buttonimage id="happiness1" size="204 17" pos="58 43" source="minecolonies:textures/gui/bookmark_ribbon_01.png" visible="false"
                 label="$(com.minecolonies.coremod.gui.workerhuts.happiness)"
                 textalign="MIDDLE_LEFT" textoffset="35 2" textcolor="White" textdisabledcolor="DarkGray"/>

    <buttonimage id="infoExt" pos="-17 73" size="104 14" source="minecolonies:textures/gui/bookmark_medium_ribbon_01.png" visible="false"
                 label="$(com.minecolonies.coremod.gui.workerhuts.information)"
                 textalign="MIDDLE_LEFT" textcolor="White" textoffset="8 1" enabled="false"/>
    <buttonimage id="actionsExt" pos="-17 97" size="104 14" source="minecolonies:textures/gui/bookmark_medium_ribbon_02.png" visible="false"
                 label="$(com.minecolonies.coremod.gui.townHall.actions)"
                 textalign="MIDDLE_LEFT" textcolor="White" textoffset="8 1" enabled="false"/>
    <buttonimage id="permissionsExt" pos="-17 121" size="104 14" source="minecolonies:textures/gui/bookmark_medium_ribbon_03.png" visible="false"
                 label="$(com.minecolonies.coremod.gui.townHall.permissions)"
                 textalign="MIDDLE_LEFT" textcolor="White" textoffset="8 1" enabled="false"/>
    <buttonimage id="citizensExt" pos="-17 145" size="104 14" source="minecolonies:textures/gui/bookmark_medium_ribbon_04.png" visible="false"
                 label="$(com.minecolonies.coremod.gui.townHall.citizens)"
                 textalign="MIDDLE_LEFT" textcolor="White" textoffset="8 1" enabled="false"/>
    <buttonimage id="settingsExt" pos="-17 169" size="104 14" source="minecolonies:textures/gui/bookmark_medium_ribbon_05.png" visible="false"
                 label="$(com.minecolonies.coremod.gui.workerhuts.settings)"
                 textalign="MIDDLE_LEFT" textcolor="White" textoffset="8 1" enabled="false"/>
    <buttonimage id="workOrderExt" pos="-17 193" size="104 14" source="minecolonies:textures/gui/bookmark_medium_ribbon_06.png" visible="false"
                 label="$(com.minecolonies.coremod.gui.workerhuts.workOrder)"
                 textalign="MIDDLE_LEFT" textcolor="White" textoffset="8 1" enabled="false"/>
    <buttonimage id="happinessExt" pos="-17 217" size="104 14" source="minecolonies:textures/gui/bookmark_medium_ribbon_01.png" visible="false"
                 label="$(com.minecolonies.coremod.gui.workerhuts.happiness)"
                 textalign="MIDDLE_LEFT" textcolor="White" textoffset="8 1" enabled="false"/>

    <!-- onHoverId="infoExt" onHoverId="actionsExt" onHoverId="permissionsExt" onHoverId="citizensExt" onHoverId="settingsExt" onHoverId="workOrderExt" onHoverId="happinessExt" -->
    <buttonimage id="infopage" size="17 17" pos="62 71"
                 source="minecolonies:textures/gui/red_wax_information.png"/>
    <buttonimage id="actions" size="17 17" pos="62 95"
                 source="minecolonies:textures/gui/red_wax_actions.png"/>
    <buttonimage id="permissions" size="17 17" pos="62 119"
                 source="minecolonies:textures/gui/red_wax_permissions.png"/>
    <buttonimage id="citizens" size="17 17" pos="62 143"
                 source="minecolonies:textures/gui/red_wax_citizens.png"/>
    <buttonimage id="settings" size="17 17" pos="62 167"
                 source="minecolonies:textures/gui/red_wax_settings.png"/>
    <buttonimage id="workOrder" size="17 17" pos="62 191"
                 source="minecolonies:textures/gui/red_wax_work_orders.png"/>
    <!-- todo Create the texture -->
    <buttonimage id="happiness" size="17 17" pos="62 215"
                 source="minecolonies:textures/gui/red_wax_information.png"/>

    <switch id="pages" size="374 243" pos="75 0">
        <view id="pageActions">
            <layout source="minecolonies:gui/townhall/layoutactions.xml"/>
        </view>
        <view id="pageInfo">
            <layout source="minecolonies:gui/townhall/layoutinfo.xml"/>
        </view>
        <view id="pagePermissions">
            <layout source="minecolonies:gui/townhall/layoutpermissions.xml"/>
        </view>
        <view id="pageCitizens">
            <layout source="minecolonies:gui/townhall/layoutcitizens.xml"/>
        </view>
        <view id="pageSettings">
            <layout source="minecolonies:gui/townhall/layoutsettings.xml"/>
        </view>
        <view id="pageHappiness">
            <layout source="minecolonies:gui/townhall/layouthappiness.xml"/>
        </view>
        <view id="pageWorkOrder">
            <layout source="minecolonies:gui/townhall/layoutworkorder.xml"/>
        </view>
    </switch>
    <buttonimage id="prevPage" size="18 10" pos="100 24" source="minecolonies:textures/gui/builderhut/turn_page_left.png"/>
    <buttonimage id="nextPage" size="18 10" pos="406 24" source="minecolonies:textures/gui/builderhut/turn_page_right.png"/>
    <label id="pageNum" size="18 9" pos="406 211" textalign="MIDDLE" label="" color="black"/>
</window>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/windowresourcescroll.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" size="190 244" pause="false"
        lightbox="false"
        xsi:noNamespaceSchemaLocation="file:../../../../java/com/minecolonies/blockout/blockOut.xsd">

    <image source="minecolonies:textures/gui/builderhut/builder_papper_sketch.png" size="100% 100%"/>
    <image source="minecolonies:textures/gui/builderhut/builder_charcoal_chalk.png" size="19 59" pos="175 180"/>

    <label size="100% 11" pos="0 10"
           label="$(com.minecolonies.coremod.gui.workerHuts.resourceList)" color="black"
           textalign="BOTTOM_MIDDLE"/>

    <label size="100% 11" pos="0 22" id="constructionName"
           label="" color="black"
           textalign="BOTTOM_MIDDLE"/>

    <list id="resources" size="78% 75%" pos="30 40">
        <box size="100% 30" linewidth="2">
            <itemicon id="resourceIcon" size="16 16" pos="1 1"/>
            <label id="resourceName" size="100 12" pos="20 3" textalign="MIDDLE_LEFT" color="black"/>
            <label id="resourceMissing" size="50 12" pos="2 18" textalign="MIDDLE_LEFT" color="black"/>
            <label id="resourceAvailableNeeded" size="100% 12" pos="0 18" textalign="MIDDLE" color="black"/>

            <label id="resourceId" size="1 1" pos="100 100"/>
            <label id="resourceQuantity" size="1 1" pos="100 100"/>
        </box>
    </list>
</window>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/windowhutcrusher.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" size="190 244" pause="false"
        lightbox="false"
        xsi:noNamespaceSchemaLocation="file:../../../../../api/java/com/minecolonies/blockout/blockOut.xsd">
    <switch id="pages" size="100% 100%">
        <view id="pageActions" size="100% 100%">
            <layout source="minecolonies:gui/layouthuts/layouthutpageactions.xml"/>
        </view>
        <view id="crusherSettings" size="100% 100%">
            <image source="minecolonies:textures/gui/builderhut/builder_paper.png" size="190 244"/>
            <label size="130 11" pos="30 14" textalign="MIDDLE" color="black"
                   label="$(com.minecolonies.coremod.gui.workerhuts.crusherSettings):"/>

            <buttonimage id="block" size="86 17" pos="25 60" textcolor="black"
                         source="minecolonies:textures/gui/builderhut/builder_button_medium.png"/>
            <input id="qty" size="50 18" pos="115 60" maxlength="25"/>
            <buttonimage id="save" size="86 17" pos="52 214" textcolor="black"
                         source="minecolonies:textures/gui/builderhut/builder_button_medium.png" label="$(com.minecolonies.coremod.gui.workerhuts.save)"/>
        </view>
    </switch>
    <buttonimage id="prevPage" size="18 10" pos="13 13" source="minecolonies:textures/gui/builderhut/turn_page_left.png"/>
    <buttonimage id="nextPage" size="18 10" pos="159 13" source="minecolonies:textures/gui/builderhut/turn_page_right.png"/>
    <label id="pageNum" size="20 11" pos="158 222" textalign="MIDDLE" label="" color="black"/>
</window>
