=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/blockOut.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="window" type="windowType"/>
    <xs:element name="layout" type="layoutType"/>

    <xs:complexType name="windowType">
        <xs:group ref="paneContainerGroup" minOccurs="0" maxOccurs="unbounded"/>
        <xs:attribute name="inherit"  type="xs:string"/>
        <xs:attribute name="size"     type="xs:string"/>
        <xs:attribute name="width"    type="xs:string"/>
        <xs:attribute name="height"   type="xs:string"/>
        <xs:attribute name="lightbox" type="xs:boolean"/>
        <xs:attribute name="pause"    type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="layoutType">
        <xs:group ref="paneContainerGroup" minOccurs="0" maxOccurs="unbounded"/>
    </xs:complexType>

    <!-- Pane basic attributes -->
    <xs:complexType name="paneType">
        <xs:attribute name="id"      type="xs:string"/>

        <xs:attribute name="align"   type="xs:string"/>
        <xs:attribute name="size"    type="xs:string"/>
        <xs:attribute name="width"   type="xs:string"/>
        <xs:attribute name="height"  type="xs:string"/>
        <xs:attribute name="pos"     type="xs:string"/>
        <xs:attribute name="x"       type="xs:string"/>
        <xs:attribute name="y"       type="xs:string"/>

        <xs:attribute name="visible" type="xs:boolean"/>
        <xs:attribute name="enabled" type="xs:boolean"/>

        <xs:attribute name="style"   type="xs:string"/>
    </xs:complexType>

    <!-- View basic attributes and contents -->
    <xs:complexType name="viewType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:group ref="paneContainerGroup" minOccurs="0" maxOccurs="unbounded"/>
                <xs:attribute name="padding" type="xs:integer"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- Master group for all panes that can be used -->
    <xs:group name="paneContainerGroup">
        <xs:choice>
            <xs:element name="layout"       type="layoutElementType"/>
            <xs:element name="view"         type="viewType"/>
            <xs:element name="group"        type="groupType"/>
            <!-- xs:element name="scrollgroup"  type="scrollGroupType"/ -->
            <xs:element name="list"         type="listType"/>
            <xs:element name="button"       type="buttonType"/>
            <xs:element name="buttonimage"  type="buttonImageType"/>
            <xs:element name="label"        type="labelType"/>
            <xs:element name="input"        type="inputType"/>
            <xs:element name="image"        type="imageType"/>
            <xs:element name="box"          type="boxType"/>
            <xs:element name="itemicon"     type="itemIconType"/>
            <xs:element name="switch"       type="switchType"/>
        </xs:choice>
    </xs:group>

    <!-- <layout> -->
    <xs:complexType name="layoutElementType">
        <xs:attribute name="source" use="required"/>
    </xs:complexType>

    <!-- <group> -->
    <xs:complexType name="groupType">
        <xs:complexContent>
            <xs:extension base="viewType">
                <xs:attribute name="spacing" type="xs:integer"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <switch> -->
    <xs:complexType name="switchType">
        <xs:complexContent>
            <xs:extension base="viewType">
                <xs:attribute name="default" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <box> -->
    <xs:complexType name="boxType">
        <xs:complexContent>
            <xs:extension base="viewType">
                <xs:attribute name="color" type="xs:string"/>
                <xs:attribute name="linewidth" type="xs:decimal"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <list> -->
    <xs:complexType name="listType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:group ref="paneContainerGroup" minOccurs="1" maxOccurs="1"/>
                <xs:attribute name="padding" type="xs:integer"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <button> -->
    <xs:complexType name="buttonType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="label"      type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <label> -->
    <xs:complexType name="labelType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="label"      type="xs:string"/>
                <xs:attribute name="textscale"  type="xs:string"/>
                <xs:attribute name="textalign"  type="xs:string"/>
                <xs:attribute name="color"      type="xs:string"/>
                <xs:attribute name="hovercolor" type="xs:string"/>
                <xs:attribute name="shadow"     type="xs:boolean"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <itemicon> -->
    <xs:complexType name="itemIconType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="item" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <buttonimage> -->
    <xs:complexType name="buttonImageType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <!-- Image and Highlight -->
                <xs:attribute name="source"          type="xs:string" use="required"/>
                <xs:attribute name="imageoffset"     type="xs:string"/>
                <xs:attribute name="imagesize"       type="xs:string"/>
                <xs:attribute name="highlight"       type="xs:string"/>
                <xs:attribute name="highlightoffset" type="xs:string"/>
                <xs:attribute name="highlightsize"   type="xs:string"/>
                <!-- Label (optional) -->
                <xs:attribute name="label"      type="xs:string"/>
                <xs:attribute name="textscale"       type="xs:string"/>
                <xs:attribute name="textalign"       type="xs:string"/>
                <xs:attribute name="textoffset"      type="xs:string"/>
                <xs:attribute name="textcolor"       type="xs:string"/>
                <xs:attribute name="texthovercolor"  type="xs:string"/>
                <xs:attribute name="textdisabledcolor" type="xs:string"/>
                <xs:attribute name="shadow"          type="xs:boolean"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <image> -->
    <xs:complexType name="imageType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="source" type="xs:string"/>
                <xs:attribute name="imageoffset" type="xs:string"/>
                <xs:attribute name="imagesize" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <input> -->
    <xs:complexType name="inputType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="text"          type="xs:string"/>
                <xs:attribute name="maxlength"     type="xs:integer"/>
                <xs:attribute name="color"         type="xs:string"/>
                <xs:attribute name="colordisabled" type="xs:string"/>
                <xs:attribute name="shadow"        type="xs:boolean"/>
                <xs:attribute name="tab"           type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

</xs:schema>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/windowhutuniversity.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" size="190 244" pause="false"
        lightbox="false"
        xsi:noNamespaceSchemaLocation="file:../../../../../api/java/com/minecolonies/blockout/blockOut.xsd">
    <switch id="pages" size="100% 100%">
        <view id="pageActions" size="100% 100%">
            <layout source="minecolonies:gui/layouthuts/layouthutpageactions.xml"/>
        </view>
        <view id="pageBranches" size="100% 100%">
            <image source="minecolonies:textures/gui/builderhut/builder_paper.png" size="190 244"/>
            <label id="title" size="130 11" pos="30 13" color="black" textalign="MIDDLE" label="$(com.minecolonies.coremod.gui.research.title)"/>
            <label id="maxresearchwarn" size="180 10" pos="10 28" color="black" textalign="MIDDLE"/>
            <list id="researches" size="164 175" pos="10 40">
                <box size="100% 28" linewidth="0">
                    <buttonimage id="name" size="129 17" pos="2 10" align="MIDDLE" textcolor="black"
                                 source="minecolonies:textures/gui/builderhut/builder_button_medium_large.png"
                                 disabled="minecolonies:textures/gui/builderhut/builder_button_medium_large_disabled.png" disabledsize="129 17"/>
                </box>
            </list>
        </view>
    </switch>
    <buttonimage id="prevPage" size="18 10" pos="13 13" source="minecolonies:textures/gui/builderhut/turn_page_left.png"/>
    <buttonimage id="nextPage" size="18 10" pos="159 13" source="minecolonies:textures/gui/builderhut/turn_page_right.png"/>
    <label id="pageNum" size="20 11" pos="158 222" textalign="MIDDLE" label="" color="black"/>
</window>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/windowguardcontrol.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" size="420 240" pause="false"
        lightbox="false" xsi:noNamespaceSchemaLocation="file:../../../../../api/java/com/minecolonies/blockout/blockOut.xsd">
    <label size="50 11" pos="42 12" label="$(com.minecolonies.coremod.gui.workerhuts.patrol)" color="white" style="bold"/>
    <buttonimage id="patrol" size="86 17" pos="42 23"
                 source="minecolonies:textures/gui/builderhut/builder_button_medium.png"
                 label="$(com.minecolonies.coremod.gui.workerhuts.modeA)" textcolor="black"/>

    <label size="50 11" pos="12 42" label="$(com.minecolonies.coremod.gui.workerhuts.retrieve)" color="white" style="bold"/>
    <buttonimage id="retrieve" size="86 17" pos="42 53"
                 source="minecolonies:textures/gui/builderhut/builder_button_medium.png"
                 label="$(com.minecolonies.coremod.gui.workerhuts.retrieveOff)" textcolor="black"/>

    <label size="50 11" pos="12 62" label="$(com.minecolonies.coremod.gui.workerhuts.trainees)" color="white" style="bold"/>
    <buttonimage id="trainees" size="86 17" pos="42 83"
                 source="minecolonies:textures/gui/builderhut/builder_button_medium.png"
                 label="$(com.minecolonies.coremod.gui.workerhuts.retrieveOff)" textcolor="black"/>

    <button id="patrolling" size="50 14" pos="15 102"
            label="$(com.minecolonies.coremod.gui.workerhuts.task.patrol)"/>
    <button id="following" size="50 14" pos="67 102"
            label="$(com.minecolonies.coremod.gui.workerhuts.task.follow)"/>
    <button id="guarding" size="50 14" pos="119 102"
            label="$(com.minecolonies.coremod.gui.workerhuts.task.guard)"/>

    <buttonimage id="setTarget" size="129 17" pos="25 130"
                 source="minecolonies:textures/gui/builderhut/builder_button_medium_large.png"
                 label="$(com.minecolonies.coremod.gui.workerhuts.setTarget)" textcolor="black"/>

    <list id="positions" size="129 100" pos="25 152">
        <box size="100% 15" linewidth="2">
            <label id="position" size="100 12" pos="5 2" color="white"/>
        </box>
    </list>

    <list id="workers" size="129 180" pos="300 12">
        <box size="100% 45" linewidth="0">
            <label id="name" size="100% 12" color="white" pos="0 0"/>
            <label id="position" size="75 12" pos="0 12" color="white"/>
            <label id="level" size="75 12" color="white" pos="80 12"/>
            <view id="healthBar" size="100% 12" pos="0 15">
                <label id="healthLabel" size="30 11" color="black" pos="115 10"/>
            </view>
        </box>
    </list>
</window>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/windowbuildbuilding.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" pause="true"
        lightbox="true"
        xsi:noNamespaceSchemaLocation="file:../../../../java/com/minecolonies/blockout/blockOut.xsd">

    <buttonimage id="previousStyle" size="14 15"  pos="140 0" label="&lt;"
                 source="minecolonies:textures/gui/builderhut/builder_button_mini.png" textcolor="black"/>
    <dropdown id="style" size="129 17" pos="155 0" maxContentHeight="75" dropDownSize="140 75" source="minecolonies:textures/gui/builderhut/builder_button_medium_large.png" textcolor="black">
        <view size="100% 15">
            <label id="id" size="100% 100%" label="" pos="0 0"/>
            <buttonimage id="button" size="129 17"  pos="0 0"
                         source="minecolonies:textures/gui/builderhut/builder_button_medium_large.png" textcolor="black"/>
        </view>
    </dropdown>
    <buttonimage id="nextStyle" size="14 15" pos="285 0" label="&gt;"
                 source="minecolonies:textures/gui/builderhut/builder_button_mini.png" textcolor="black"/>

    <list id="resources" size="80% 80%" pos="30 20">
        <box size="100% 30" linewidth="2">
            <itemicon id="resourceIcon" size="24 24" pos="1 1"/>
            <label id="resourceName" size="140 12" pos="30 9" color="white"/>
            <label id="resourceQuantity" size="12 12" pos="170 9" color="white"/>
        </box>
    </list>
    <buttonimage id="cancel" align="TOP_MIDDLE" size="129 17" pos="-120 220"
                 source="minecolonies:textures/gui/builderhut/builder_button_medium_large.png"
                 label="$(gui.cancel)" textcolor="black"/>
    <buttonimage id="build" align="TOP_MIDDLE" size="129 17" pos="10 220"
                 source="minecolonies:textures/gui/builderhut/builder_button_medium_large.png"
                 label="$(com.minecolonies.coremod.gui.workerHuts.upgrade)" textcolor="black"/>
    <buttonimage id="reposition" align="TOP_MIDDLE" size="129 17" pos="140 220"
                 source="minecolonies:textures/gui/builderhut/builder_button_medium_large.png"
                 label="$(com.minecolonies.coremod.gui.workerHuts.reposition)" textcolor="black"/>
</window>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/windowselectres.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" pause="false"
        lightbox="true" xsi:noNamespaceSchemaLocation="file:../../../../java/com/ldtteam/blockout/blockOut.xsd">
    <label size="100% 11" pos="0 25" textalign="TOP_MIDDLE" color="white"
           label="$(com.minecolonies.coremod.gui.scan.select.title)"/>

    <input id="name" size="150 18" pos="135 40" maxlength="25"/>

    <itemicon id="resourceIcon" size="17 17" pos="70 1"/>
    <label id="resourceName" size="140 12" pos="100 4" color="white"/>

    <input id="qty" size="25 14" pos="200 2" maxlength="25"/>
    <label id="qtylabel" label="$(com.minecolonies.coremod.gui.scan.select.stack)" size="50 12" pos="235 4"/>

    <list id="resources" size="300 120" pos="60 65">
        <box size="100% 17" linewidth="2">
            <itemicon id="resourceIcon" size="17 17" pos="1 1"/>
            <label id="resourceName" size="140 12" pos="30 1" color="white"/>
            <buttonimage label="$(com.minecolonies.coremod.gui.scanTool.select)" id="select" pos="160 1" size="86 17"
                         source="minecolonies:textures/gui/builderhut/builder_button_medium.png" textcolor="black"/>
        </box>
    </list>

    <buttonimage id="done" source="minecolonies:textures/gui/buildtool/confirm.png" size="32" pos="125 185"/>
    <buttonimage id="cancel" source="minecolonies:textures/gui/buildtool/cancel.png" size="32" pos="215 185"/>
</window>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/windowhutenchanter.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" size="190 244" pause="false"
        lightbox="false"
        xsi:noNamespaceSchemaLocation="file:../../../../java/com/minecolonies/blockout/blockOut.xsd">
    <switch id="pages" size="100% 100%">
        <view id="pageActions" size="100% 100%">
            <layout source="minecolonies:gui/layouthuts/layouthutpageactions.xml"/>
        </view>
        <view id="workerPage" size="100% 100%">
            <image source="minecolonies:textures/gui/builderhut/builder_papper.png" size="190 244"/>
            <label id="desc" size="130 11" pos="30 14" label="$(com.minecolonies.gui.workerhuts.enchanter.workers)" color="black" textalign="MIDDLE"/>
            <list id="gatherWorkers" size="164 136" pos="13 40">
                <box size="100% 17" linewidth="2">
                    <label id="workerName" size="100 12" pos="5 1" color="black"/>
                    <buttonimage label="$(com.minecolonies.coremod.gui.workerHuts.retrieveOn)" id="switch" pos="125 1" size="29 15"
                                 source="minecolonies:textures/gui/builderhut/builder_button_very_small.png" textcolor="black"/>
                </box>
            </list>
            <label id="desc2" size="130 11" pos="30 180" label="$(com.minecolonies.gui.workerhuts.enchanter.daily)" color="black" textalign="MIDDLE"/>
            <input id="qty" size="25 17" pos="80 195" maxlength="25"/>
        </view>
    </switch>
    <buttonimage id="prevPage" size="18 10" pos="13 13" source="minecolonies:textures/gui/builderhut/turn_page_left.png"/>
    <buttonimage id="nextPage" size="18 10" pos="159 13" source="minecolonies:textures/gui/builderhut/turn_page_right.png"/>
    <label id="pageNum" size="20 11" pos="158 222" textalign="MIDDLE" label="" color="black"/>
</window>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/windowhutcook.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" size="190 244" pause="false"
        lightbox="false"
        xsi:noNamespaceSchemaLocation="file:../../../../java/com/minecolonies/blockout/blockOut.xsd">
    <switch id="pages" size="100% 100%">
        <view id="pageActions" size="100% 100%">
            <layout source="minecolonies:gui/layouthuts/layouthutpageactions.xml"/>
        </view>
        <view id="fuel" size="100% 100%">
            <layout source="minecolonies:gui/layouthuts/layoutfilterablelist.xml"/>
        </view>
        <view id="food" size="100% 100%">
            <layout source="minecolonies:gui/layouthuts/layoutfilterablelist.xml"/>
        </view>
        <view>
            <image source="minecolonies:textures/gui/builderhut/builder_papper.png" size="190 244"/>
            <label size="130 11" pos="30 14" textalign="MIDDLE" color="black"
                   label="$(com.minecolonies.coremod.gui.warehouse.stock)"/>
            <list id="resourcesstock" size="170 100" pos="13 50">
                <box size="100% 17" linewidth="2">
                    <itemicon id="resourceIcon" size="17 17" pos="0 0"/>
                    <label id="resourceName" size="90 12" pos="20 1" color="black"/>
                    <label id="resourceQty" size="12 12" pos="115 1" color="black"/>

                    <buttonimage label="X" id="removeStock" pos="130 1" size="29 15"
                                 source="minecolonies:textures/gui/builderhut/builder_button_very_small.png" textcolor="red"/>
                </box>
            </list>
            <buttonimage id="addStock" size="86 17" pos="50 160" textcolor="black"
                         source="minecolonies:textures/gui/builderhut/builder_button_medium.png"
                         label="$(com.minecolonies.coremod.gui.warehouse.add)"/>
        </view>
    </switch>
    <buttonimage id="prevPage" size="18 10" pos="13 13" source="minecolonies:textures/gui/builderhut/turn_page_left.png"/>
    <buttonimage id="nextPage" size="18 10" pos="159 13" source="minecolonies:textures/gui/builderhut/turn_page_right.png"/>
    <label id="pageNum" size="20 11" pos="158 222" textalign="MIDDLE" label="" color="black"/>
</window>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/windowhutbarracks.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" size="190 244" pause="false"
        lightbox="false"
        xsi:noNamespaceSchemaLocation="file:../../../../java/com/minecolonies/blockout/blockOut.xsd">
    <switch id="pages" size="100% 100%">
        <view id="pageActions" size="100% 100%">
            <layout source="minecolonies:gui/layouthutpageactionsmin.xml"/>
            <label size="166 11" pos="12 32" color="black" textalign="MIDDLE"
                label="$(com.minecolonies.coremod.gui.workerHuts.barbpoints):"/>
            <list id="positions" size="166 66" pos="12 43">
                <box size="100% 11" linewidth="1">
                    <label id="pos" size="100% 11" color="black"/>
                </box>
            </list>
        </view>
    </switch>
    <buttonimage id="prevPage" size="18 10" pos="13 13" source="minecolonies:textures/gui/builderhut/turn_page_left.png"/>
    <buttonimage id="nextPage" size="18 10" pos="159 13" source="minecolonies:textures/gui/builderhut/turn_page_right.png"/>
    <label id="pageNum" size="20 11" pos="158 222" textalign="MIDDLE" label="" color="black"/>
</window>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/windowHutFarmer.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        inherit="minecolonies:gui/windowBase.xml"
        xsi:noNamespaceSchemaLocation="file:../../../../java/com/blockout/blockOut.xsd">
    <switch id="pages" size="100% 200px" pos="0 7">
        <view id="pageActions" size="100% 100%">
            <layout source="minecolonies:gui/layoutWorkerBuildingDefault.xml"/>
        </view>
        <view id="pageSettings" size="100% 100%" pos="0 1">

            <view size="100% 100" pos="0 0">
                <label size="100% 11" pos="0 0"
                       label="Plant" color="black" textalign="BottomMiddle"/>

                <view size="100% 100" pos="0 16">
                    <itemicon size="20 20" pos="33 2" item="wheat"/>
                    <button size="30 20" pos="52 0" id="wheat"/>

                    <itemicon size="20 20" pos="90 2" item="potato"/>
                    <button size="30 20" pos="109 0" id="potato"/>

                    <itemicon size="20 20" pos="33 26" item="carrot"/>
                    <button size="30 20" pos="52 24" id="carrot"/>

                    <itemicon size="20 20" pos="90 26" item="melon"/>
                    <button size="30 20" pos="109 24" id="melon"/>

                    <itemicon size="20 20" pos="50 50" item="pumpkin"/>
                    <button size="30 20" pos="69 48" id="pumpkin"/>
                </view>
            </view>

        </view>
    </switch>

    <button id="prevPage" align="TopLeft" size="20 20" pos="10 5" label="&lt;&lt;"/>
    <button id="nextPage" align="TopRight" size="20 20" pos="10 5" label="&gt;&gt;"/>

    <button id="inventory"
            align="BottomMiddle" size="116 20" pos="0 13"
            label="$(container.inventory)"/>
</window>
