=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/blockOut.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="window" type="windowType"/>
    <xs:element name="layout" type="layoutType"/>

    <xs:complexType name="windowType">
        <xs:group ref="paneContainerGroup" minOccurs="0" maxOccurs="unbounded"/>
        <xs:attribute name="inherit"  type="xs:string"/>
        <xs:attribute name="size"     type="xs:string"/>
        <xs:attribute name="width"    type="xs:string"/>
        <xs:attribute name="height"   type="xs:string"/>
        <xs:attribute name="lightbox" type="xs:boolean"/>
        <xs:attribute name="pause"    type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="layoutType">
        <xs:group ref="paneContainerGroup" minOccurs="0" maxOccurs="unbounded"/>
    </xs:complexType>

    <!-- Pane basic attributes -->
    <xs:complexType name="paneType">
        <xs:attribute name="id"      type="xs:string"/>

        <xs:attribute name="align"   type="xs:string"/>
        <xs:attribute name="size"    type="xs:string"/>
        <xs:attribute name="width"   type="xs:string"/>
        <xs:attribute name="height"  type="xs:string"/>
        <xs:attribute name="pos"     type="xs:string"/>
        <xs:attribute name="x"       type="xs:string"/>
        <xs:attribute name="y"       type="xs:string"/>

        <xs:attribute name="visible" type="xs:boolean"/>
        <xs:attribute name="enabled" type="xs:boolean"/>

        <xs:attribute name="style"   type="xs:string"/>
    </xs:complexType>

    <!-- View basic attributes and contents -->
    <xs:complexType name="viewType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:group ref="paneContainerGroup" minOccurs="0" maxOccurs="unbounded"/>
                <xs:attribute name="padding" type="xs:integer"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- Master group for all panes that can be used -->
    <xs:group name="paneContainerGroup">
        <xs:choice>
            <xs:element name="layout"       type="layoutElementType"/>
            <xs:element name="view"         type="viewType"/>
            <xs:element name="group"        type="groupType"/>
            <!-- xs:element name="scrollgroup"  type="scrollGroupType"/ -->
            <xs:element name="list"         type="listType"/>
            <xs:element name="button"       type="buttonType"/>
            <xs:element name="buttonimage"  type="buttonImageType"/>
            <xs:element name="label"        type="labelType"/>
            <xs:element name="input"        type="inputType"/>
            <xs:element name="image"        type="imageType"/>
            <xs:element name="box"          type="boxType"/>
            <xs:element name="itemicon"     type="itemIconType"/>
            <xs:element name="switch"       type="switchType"/>
        </xs:choice>
    </xs:group>

    <!-- <layout> -->
    <xs:complexType name="layoutElementType">
        <xs:attribute name="source" use="required"/>
    </xs:complexType>

    <!-- <group> -->
    <xs:complexType name="groupType">
        <xs:complexContent>
            <xs:extension base="viewType">
                <xs:attribute name="spacing" type="xs:integer"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <switch> -->
    <xs:complexType name="switchType">
        <xs:complexContent>
            <xs:extension base="viewType">
                <xs:attribute name="default" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <box> -->
    <xs:complexType name="boxType">
        <xs:complexContent>
            <xs:extension base="viewType">
                <xs:attribute name="color" type="xs:string"/>
                <xs:attribute name="linewidth" type="xs:decimal"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <list> -->
    <xs:complexType name="listType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:group ref="paneContainerGroup" minOccurs="1" maxOccurs="1"/>
                <xs:attribute name="padding" type="xs:integer"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <button> -->
    <xs:complexType name="buttonType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="label"      type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <label> -->
    <xs:complexType name="labelType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="label"      type="xs:string"/>
                <xs:attribute name="textscale"  type="xs:string"/>
                <xs:attribute name="textalign"  type="xs:string"/>
                <xs:attribute name="color"      type="xs:string"/>
                <xs:attribute name="hovercolor" type="xs:string"/>
                <xs:attribute name="shadow"     type="xs:boolean"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <itemicon> -->
    <xs:complexType name="itemIconType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="item" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <buttonimage> -->
    <xs:complexType name="buttonImageType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <!-- Image and Highlight -->
                <xs:attribute name="source"          type="xs:string" use="required"/>
                <xs:attribute name="imageoffset"     type="xs:string"/>
                <xs:attribute name="imagesize"       type="xs:string"/>
                <xs:attribute name="highlight"       type="xs:string"/>
                <xs:attribute name="highlightoffset" type="xs:string"/>
                <xs:attribute name="highlightsize"   type="xs:string"/>
                <!-- Label (optional) -->
                <xs:attribute name="label"      type="xs:string"/>
                <xs:attribute name="textscale"       type="xs:string"/>
                <xs:attribute name="textalign"       type="xs:string"/>
                <xs:attribute name="textoffset"      type="xs:string"/>
                <xs:attribute name="textcolor"       type="xs:string"/>
                <xs:attribute name="texthovercolor"  type="xs:string"/>
                <xs:attribute name="textdisabledcolor" type="xs:string"/>
                <xs:attribute name="shadow"          type="xs:boolean"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <image> -->
    <xs:complexType name="imageType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="source" type="xs:string"/>
                <xs:attribute name="imageoffset" type="xs:string"/>
                <xs:attribute name="imagesize" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <input> -->
    <xs:complexType name="inputType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="text"          type="xs:string"/>
                <xs:attribute name="maxlength"     type="xs:integer"/>
                <xs:attribute name="color"         type="xs:string"/>
                <xs:attribute name="colordisabled" type="xs:string"/>
                <xs:attribute name="shadow"        type="xs:boolean"/>
                <xs:attribute name="tab"           type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

</xs:schema>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/citizen/layouts/main.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" size="290 244"
        xsi:noNamespaceSchemaLocation="file:../../../../../../java/com/minecolonies/blockout/blockOut.xsd">
    <image source="minecolonies:textures/gui/citizen/colonist_papper_sketch.png" size="190 244"/>

    <label id="name" size="100% 11" color="black" pos="50 14"/>
    <image id="deco1" size="82 16" source="minecolonies:textures/gui/citizen/colonist_text_decor_down.png" pos="50 29"/>

    <view id="healthBar" size="100% 11" pos="30 42"/>
    <view id="saturationBar" size="100% 11" pos="30 54"/>
    <view id="xpBar" size="100% 11" pos="30 66"/>
    <label id="xpLabel" size="100% 11" color="black" pos="145 72"/> 
    <view id="happinessBar" size="100% 11" pos="30 72"/> 
    <label id="happinessLabel" size="100% 11" color="black" pos="145 83"/> 
    
    <image id="deco2" size="73 16" pos="16 99"
        source="minecolonies:textures/gui/citizen/colonist_decor_down.png"/>
    <label id="title" size="100% 11" pos="40 107" color="black"
        label="Â§l$(com.minecolonies.coremod.gui.citizen.skills)"/>
    <group size="100% 100%" pos="22 119">
        <label id="strength" size="100% 11" color="black"/>
        <label id="endurance" size="100% 11" color="black"/>
        <label id="charisma" size="100% 11" color="black"/>
        <label id="intelligence" size="100% 11" color="black"/>
        <label id="dexterity" size="100% 11" color="black"/>
    </group>
    <image id="deco3" size="73 16" pos="16 172"
        source="minecolonies:textures/gui/citizen/colonist_decor_up.png"/>

    <buttonimage id="requestsTitle" size="80 48" pos="195 64" label="$(com.minecolonies.coremod.gui.citizen.requestTitle)"
                source="minecolonies:textures/gui/citizen/colonist_request_button.png" textcolor="black"/>
    <buttonimage id="inventory" size="80 49" pos="195 119" label="$(container.inventory)"
                source="minecolonies:textures/gui/citizen/colonist_inventory_button.png" textcolor="black" shadow="false"/>

    <image id="deco4" size="15 49" pos="37 194"
        source="minecolonies:textures/gui/citizen/colonist_decor_up_ribbon_smaller.png"/>
    <image id="gender" size="30 30" pos="30 189"
        source="minecolonies:textures/gui/citizen/colonist_wax_male_smaller.png"/>
</window>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/windowhutsifter.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" size="190 244" pause="false"
        lightbox="false"
        xsi:noNamespaceSchemaLocation="file:../../../../java/com/minecolonies/blockout/blockOut.xsd">
    <switch id="pages" size="100% 100%">
        <view id="pageActions" size="100% 100%">
            <layout source="minecolonies:gui/layouthuts/layouthutpageactions.xml"/>
        </view>
        <view id="sifterSettings" size="100% 100%">
            <image source="minecolonies:textures/gui/builderhut/builder_papper.png" size="190 244"/>
            <label size="130 11" pos="30 24" textalign="MIDDLE" color="black"
                   label="$(com.minecolonies.coremod.gui.workerHuts.sifterSettings):"/>

            <buttonimage id="block" size="86 17" pos="25 40" textcolor="black"
                         source="minecolonies:textures/gui/builderhut/builder_button_medium.png"/>
            <input id="qty" size="50 18" pos="115 40" maxlength="25"/>
            <buttonimage id="save" size="86 17" pos="52 60" textcolor="black"
                         source="minecolonies:textures/gui/builderhut/builder_button_medium.png" label="$(com.minecolonies.coremod.gui.workerHuts.save)"/>


            <label size="130 11" pos="30 100" textalign="MIDDLE" color="black"
                   label="$(com.minecolonies.coremod.gui.workerHuts.meshSettings):"/>
            <list id="resources" size="164 136" pos="13 120">
                <box size="100% 17" linewidth="2">
                    <itemicon id="resourceIcon" size="17 17" pos="0 0"/>
                    <label id="resourceName" size="100 12" pos="20 1" color="white"/>
                    <buttonimage label="$(com.minecolonies.coremod.gui.workerHuts.buy)" id="buyMesh" pos="120 1" size="29 15"
                                 source="minecolonies:textures/gui/builderhut/builder_button_very_small.png" textcolor="black"/>
                </box>
            </list>

        </view>
    </switch>
    <buttonimage id="prevPage" size="18 10" pos="13 13" source="minecolonies:textures/gui/builderhut/turn_page_left.png"/>
    <buttonimage id="nextPage" size="18 10" pos="159 13" source="minecolonies:textures/gui/builderhut/turn_page_right.png"/>
    <label id="pageNum" size="20 11" pos="158 222" textalign="MIDDLE" label="" color="black"/>
</window>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/townhall/windowtownhallmercenary.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" pause="true"
        lightbox="true"
        xsi:noNamespaceSchemaLocation="file:../../../../java/com/minecolonies/blockout/blockOut.xsd">

    <image source="minecolonies:textures/gui/citizen/colonist_papper_sketch.png" pos="150 0" size="152 145"/>
    <image size="82 16" source="minecolonies:textures/gui/citizen/colonist_text_decor_down.png" pos="190 9"/>
    <image source="minecolonies:textures/gui/citizen/colonist_wax_male.png" pos="160 110" size="30 30"/>
    <image source="minecolonies:textures/items/moneygold.png" pos="170 60" size="20 20"/>
    <image source="minecolonies:textures/items/moneygold.png" pos="170 90" size="20 20"/>
    <image source="minecraft:textures/item/diamond_sword.png" pos="200 60" size="40 40"/>

    <button id="done" size="200 20" pos="110 170" label="$(com.minecolonies.coremod.gui.townHall.mercenaryHire)"/>
    <button id="cancel" size="200 20" pos="110 194" label="$(gui.cancel)"/>

    <text id="text" size="145 90" pos="10 55" color="white" text="$(com.minecolonies.coremod.gui.townHall.mercenaryStory)"/>

</window>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/windowhutlumberjack.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" size="190 244" pause="false"
        lightbox="false"
        xsi:noNamespaceSchemaLocation="file:../../../../java/com/minecolonies/blockout/blockOut.xsd">
    <switch id="pages" size="100% 100%">
        <view id="pageActions" size="100% 100%">
            <layout source="minecolonies:gui/layouthuts/layouthutpageactions.xml"/>
        </view>
        <view id="saplings" size="100% 100%">
            <layout source="minecolonies:gui/layouthuts/layoutfilterablelist.xml"/>
        </view>
        <view id="settings" size="100% 100%">
            <image source="minecolonies:textures/gui/builderhut/builder_papper.png" size="190 244"/>
            <label id="desc" size="130 11" pos="70 15" color="black" label="$(com.minecolonies.coremod.gui.workerHuts.settings)"/>

            <buttonimage id="saplingReplant" textcolor="black" size="86 17" pos="50 70" source="minecolonies:textures/gui/builderhut/builder_button_medium.png"/>
            <buttonimage id="toggleRestriction" textcolor="black" size="86 17" pos="50 90" source="minecolonies:textures/gui/builderhut/builder_button_medium.png"/>
            <buttonimage id="giveTool" textcolor="black" size="86 17" pos="50 110" source="minecolonies:textures/gui/builderhut/builder_button_medium.png"/>
        </view>
    </switch>
    <buttonimage id="prevPage" size="18 10" pos="13 13" source="minecolonies:textures/gui/builderhut/turn_page_left.png"/>
    <buttonimage id="nextPage" size="18 10" pos="159 13" source="minecolonies:textures/gui/builderhut/turn_page_right.png"/>
    <label id="pageNum" size="20 11" pos="158 222" textalign="MIDDLE" label="" color="black"/>
</window>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/layoutWorkerBuildingDefault.xml
<layout xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="file:../../../../java/com/minecolonies/blockout/blockOut.xsd">
    <label id="name" size="100% 11" pos="0 0"
           textalign="MIDDLE" color="red"/>
    <label size="100% 11" pos="0 18"
           label="$(com.minecolonies.coremod.gui.workerHuts.workerAssigned)"
           textalign="MIDDLE" color="black"/>
    <label id="workerName" size="100% 11" pos="0 28"
           textalign="MIDDLE" color="black"/>
    <label id="workerLevel" size="100% 11" pos="0 44"
           textalign="MIDDLE" color="black"/>

    <button id="hire" align="TOP_MIDDLE" size="116 20" pos="0 60"
            label="$(com.minecolonies.coremod.gui.workerHuts.hire)"/>
    <button id="recall" align="TOP_MIDDLE" size="116 20" pos="0 82"
            label="$(com.minecolonies.coremod.gui.workerHuts.recall)"/>
    <button id="build" align="TOP_MIDDLE" size="116 20" pos="0 104"
            label="$(com.minecolonies.coremod.gui.workerHuts.upgrade)"/>
    <button id="repair" align="TOP_MIDDLE" size="116 20" pos="0 126"
            label="$(com.minecolonies.coremod.gui.workerHuts.repair)"/>
    <button id="recipelist" align="TOP_MIDDLE" size="116 20" pos="0 150"
            label="$(com.minecolonies.coremod.gui.workerHuts.listRecipes)"/>
    <button id="crafting" align="TOP_MIDDLE" size="116 20" pos="0 172"
            label="$(com.minecolonies.coremod.gui.workerHuts.crafting)"/>
</layout>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/windowhutfarmer.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" size="190 244" pause="false"
        lightbox="false"
        xsi:noNamespaceSchemaLocation="file:../../../../../api/java/com/minecolonies/blockout/blockOut.xsd">
    <switch id="pages" size="100% 100%">
        <view id="pageActions" size="100% 100%">
            <layout source="minecolonies:gui/layouthuts/layouthutpageactions.xml"/>
        </view>
        <view id="pageFields" size="100% 100%">
            <image source="minecolonies:textures/gui/builderhut/builder_papper.png" size="190 244"/>
            <label size="130 11" pos="30 14" color="black" textalign="MIDDLE"
                   label="$(com.minecolonies.coremod.gui.workerhuts.farmerhut.fields):"/>
            <label id="AssignmentModeLabel" size="164 11" pos="13 29" color="black" textalign="MIDDLE"
                   label="$(com.minecolonies.coremod.gui.workerhuts.farmerhut.assignmentmode)"/>
            <button id="assignmentMode" size="60 15" pos="65 42"
                    label="$(com.minecolonies.coremod.gui.hiring.off)"/>

            <list id="fields" size="164 154" pos="13 60">
                <box size="100% 34" linewidth="2">
                    <itemicon id="icon" size="16 16" pos="1 1"/>
                    <label id="worker" color="black" pos="20 2" size="130 9"/>
                    <label id="dist" color="black" pos="20 12" size="65 9"/>
                    <label id="dir" color="black" pos="20 22" size="65 9"/>
                    <button id="assignFarm" pos="100 16" size="50 15"/>
                </box>
            </list>
        </view>
        <view>
            <image source="minecolonies:textures/gui/builderhut/builder_papper.png" size="190 244"/>
            <label id="RequestFertilizerLabel" size="164 18" pos="13 29" color="black" textalign="MIDDLE"
                   label="$(com.minecolonies.coremod.gui.workerhuts.farmerhut.requestfertilizer)"/>
            <button id="requestFert" size="60 15" pos="65 50"
                    label="$(com.minecolonies.coremod.gui.requestfert.on)"/>
        </view>
    </switch>
    <buttonimage id="prevPage" size="18 10" pos="13 13" source="minecolonies:textures/gui/builderhut/turn_page_left.png"/>
    <buttonimage id="nextPage" size="18 10" pos="159 13" source="minecolonies:textures/gui/builderhut/turn_page_right.png"/>
    <label id="pageNum" size="20 11" pos="158 222" textalign="MIDDLE" label="" color="black"/>
</window>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/windowscantool.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" size="420 240" pause="false"
        lightbox="false" xsi:noNamespaceSchemaLocation="file:../../../../java/com/minecolonies/blockout/blockOut.xsd">

    <label size="100% 11" pos="60 10" color="white" label="$(com.minecolonies.coremod.gui.scanTool.from)"/>
    <input id="pos1x" size="36 18" pos="90 5" maxlength="10"/>
    <input id="pos1y" size="36 18" pos="130 5" maxlength="10"/>
    <input id="pos1z" size="36 18" pos="170 5" maxlength="10"/>

    <label size="100% 11" pos="220 10" color="white" label="$(com.minecolonies.coremod.gui.scanTool.to)"/>
    <input id="pos2x" size="36 18" pos="240 5" maxlength="10"/>
    <input id="pos2y" size="36 18" pos="280 5" maxlength="10"/>
    <input id="pos2z" size="36 18" pos="320 5" maxlength="10"/>

    <label size="100% 11" pos="72 35" color="white" label="$(com.minecolonies.coremod.gui.scanTool.name)"/>
    <input id="name" size="178 18" pos="130 30" maxlength="25"/>

    <buttonimage id="confirm" source="minecolonies:textures/gui/buildtool/confirm.png" size="32" pos="145 50"/>
    <buttonimage id="cancel" source="minecolonies:textures/gui/buildtool/cancel.png" size="32" pos="235 50"/>

    <buttonimage label="$(com.minecolonies.coremod.gui.scanTool.showRes)" id="showRes" pos="140 80" size="129 17"
                 source="minecolonies:textures/gui/builderhut/builder_button_medium_large.png" textcolor="black"/>
    <input id="filter" size="129 17" pos="140 80" maxlength="25" visible="false"/>

    <list id="resources" size="200 120" pos="10 100">
        <box size="100% 30" linewidth="2">
            <itemicon id="resourceIcon" size="17 17" pos="1 1"/>
            <label id="resourceName" size="140 12" pos="30 1" color="white"/>
            <label id="resourceQuantity" size="12 12" pos="170 1" color="white"/>
            <buttonimage label="$(com.minecolonies.coremod.gui.scanTool.remove)" id="removeBlock" pos="20 13" size="86 17"
                         source="minecolonies:textures/gui/builderhut/builder_button_medium.png" textcolor="black"/>
            <buttonimage label="$(com.minecolonies.coremod.gui.scanTool.replace)" id="replaceBlock" pos="105 13" size="86 17"
                         source="minecolonies:textures/gui/builderhut/builder_button_medium.png" textcolor="black"/>
        </box>
    </list>

    <list id="entities" size="200 100" pos="220 100">
        <box size="100% 30" linewidth="2">
            <label id="resourceName" size="140 12" pos="30 1" color="white"/>
            <buttonimage label="$(com.minecolonies.coremod.gui.scanTool.remove)" id="removeEntity" pos="40 13" size="86 17"
                         source="minecolonies:textures/gui/builderhut/builder_button_medium.png" textcolor="black"/>
        </box>
    </list>
</window>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/citizen/layouts/requests.xml
<layout xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" size="250 244" pause="false"
        lightbox="false"
        xsi:noNamespaceSchemaLocation="file:../../../../java/com/minecolonies/blockout/blockOut.xsd">

    <image source="minecolonies:textures/gui/citizen/colonist_papper.png" pos="0 -15" size="190 244"/>


    <label size="100% 11" pos="60 0"
           label="$(com.minecolonies.coremod.gui.citizen.requests)" color="black"/>
    <list id="requests" size="67% 170px" pos="12 20">
        <box id="requestx" size="100% 40" linewidth="2">
            <!--Item icon -->
            <itemicon id="requestStack" size="16 16" pos="1 3"/>
            <image id="deliveryImage" source="minecraft:textures/misc/shadow.png" size="16 16" pos="1 3" visible="false"/>

            <!--Request name-->
            <buttonimage id="detail" size="16 16" pos="1 23" source="minecolonies:textures/gui/citizen/detail_button.png"/>


            <label id="shortDetail" size="50 12" pos="20 1" color="black"/>

            <label id="requester" size="50 12" pos="20 13" color="black"/>

            <!-- Color green if possible? -->
            <buttonimage id="fulfill" size="37 16" pos="20 23" textcolor="black"
                         label="$(com.minecolonies.coremod.gui.citizen.requestsFulfill)" source="minecolonies:textures/gui/citizen/colonist_button_small.png"/>

            <!-- button to cancel the request-->
            <buttonimage id="cancel" size="37 16" pos="110 23" textcolor="black"
                         label="$(com.minecolonies.coremod.gui.citizen.requestsCancel)" source="minecolonies:textures/gui/citizen/colonist_button_small.png"/>
        </box>
    </list>
    <buttonimage id="back" size="37 16" pos="75 199" textcolor="black"
                 label="Back" source="minecolonies:textures/gui/citizen/colonist_button_small.png"/>

</layout>
